language: c
services:
    - docker
before_install:
    - docker pull mlevs/acadopy
    - docker run -v ${TRAVIS_BUILD_DIR}:/src/ -dt mlevs/acadopy
    - export CONTAINER_NAME=$(docker ps --format "{{.Names}}")
install:
    - docker exec $CONTAINER_NAME /bin/bash --login -c 'cd /src && edm run -- pip install -r requirements.txt'
    - docker exec $CONTAINER_NAME /bin/bash --login -c 'cd /src && edm run -- python setup.py install'
script:
    - docker exec $CONTAINER_NAME /bin/bash --login -c 'cd /src/acadopy/tests && edm run -- python -m unittest discover'
